# Daily Digest Generator for Nox
# Runs every day at 9:00 AM

$Date = Get-Date -Format "yyyy-MM-dd"
$Workspace = "C:\Users\alexm\.openclaw\workspace"
$DigestPath = "$Workspace\agents\nox\reentry\DAILY_DIGESTS\$Date.md"

# Get gateway status
$GatewayStatus = openclaw gateway status 2>&1 | Out-String

# Create digest
$Digest = @"
# Nox Daily Digest — $Date

## System State

### Gateway Status
````
$GatewayStatus
````

## Today's Focus
- 

## Notes
- 

## Open Items
- 

## Questions for Nox
- 

---
*Generated by Blade at $(Get-Date -Format "yyyy-MM-dd HH:mm")*
"@

# Ensure directory exists
$DigestDir = Split-Path $DigestPath -Parent
if (!(Test-Path $DigestDir)) {
    New-Item -ItemType Directory -Path $DigestDir -Force | Out-Null
}

# Write digest
Set-Content -Path $DigestPath -Value $Digest

Write-Host "Digest created: $DigestPath"
